import "./../globals.css";
import AdminPanelLayout from "@/components/panel/panel-layout";
export const metadata = {
  title: "Next.js",
  description: "Generated by Next.js",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className="">
        <AdminPanelLayout>{children}</AdminPanelLayout>
      </body>
    </html>
  );
}
