import "./../globals.css";
import { Toaster } from 'react-hot-toast';

export const metadata = {
  title: "Next.js",
  description: "Generated by Next.js",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  // connectDB().then(() => console.log("Database connected successfully"));
  return (
    <html lang="en">
      <body className="">
      <Toaster />
        {children}</body>
    </html>
  );
}
